### ISSUE TITLE
[feature request]: ability to specify a tag that is included at the end of each block created by roam-ai, e.g. #gpt-generated

### ISSUE THREAD

**Issue by benwoodward** [LayBacc/roam-ai#1]
would be great to have GPT-generated content auto-tagged so it's easy to find them all, while contextualising the content.

**Comment by LayBacc** [comment]
would it help if the "qq" is used as a tag instead? 

I'll probably make this a configurable option

**Comment by benwoodward** [comment]
> would it help if the "qq" is used as a tag instead?

would `[[qq]]` be placed on the parent block where you typed it, or it'd be added to the blocks that `roam-ai` inserts? would be great if it were configurable, 'qq' is useful as a shortcut, but is not semantically meaningful.
