### ISSUE TITLE
Allow people to define custom prompts 

### ISSUE THREAD

**Issue by Stvad** [LayBacc/roam-ai#7]
It'd be great if one could define custom prompts that'd show up in the menu. Having a good default selection of things is helpful, but it's not feasible to include all the things and it's tedious to type out the prompt manually each time

#6  related

**Comment by LayBacc** [comment]
agreed! do you have examples of your custom prompts? 

currently, I'm hardcoding the custom prompts for different modes. but it's not yet exposed via the UI. though there probably exists a simple enough design solution

**Comment by Stvad** [comment]
as an example - I've been iterating on something that would clean up the transcripts from Otter.

One simple option is to allow people to define prompts on a special config page in roam (though maybe new settings facilities provides by plugin api would work just as well)

**Comment by LayBacc** [comment]
@Stvad I think [this release](https://github.com/Roam-Research/roam-depot/pull/514) will help: https://twitter.com/Lay_Bacc/status/1621895598747127808

(in review currently)

**Comment by LayBacc** [comment]
@Stvad I think https://github.com/Roam-Research/roam-depot/pull/514 will help: https://twitter.com/Lay_Bacc/status/1621895598747127808

(in review currently)
